### ISSUE TITLE
Slim view reveals the paste after it's been deleted

### ISSUE THREAD

**Issue by samirgunic** [DarrenOfficial/dpaste#147]
## Description

When "slim" paste view is used, and then the paste is deleted, the paste appears as if it's removed (in normal paste view) but the "slim" view reveals that it's actually persisted. I think it's purged a couple of days later, just not immediately.

## Environment

URLs:

https://dpaste.org/MRgx
https://dpaste.org/MRgx/slim

The issue is not browser-specific, I have tested with Firefox 85.0b1 and Edge 87.0.664.60 (in private sessions).

## Steps to reproduce

1. Go to https://dpaste.org/
2. Type in "Hello world!"
3. Click on "Paste Snippet"
4. Click on "Slim"
5. Copy the URL to clipboard.
6. Navigate back to previous page.
7. Click on "Delete Now"
8. Click on "Yes, Delete"
9. Paste in the slim URL and navigate to it.

## Expected result
"404 Snippet not found"

## Actual result
"Hello world!"

**Comment by bartTC** [comment]
Thank you for the detailed report. The cache is not cleared upstream (in my case Cloudflare) and thats a pretty obvious bug. 😆 For now I disabled caching completely, which solves this symptom but not the issue.

**Comment by samirgunic** [comment]
Thanks for letting me know, and keep up the good work! 🥇 This is my favorite paste service you know! 😉

**Comment by DarrenOfficial** [comment]
Resolved by using Cloudflare page rules. ![IMG_0558](https://user-images.githubusercontent.com/55406094/147626844-66f4f477-0de2-469f-b86d-d812d5aef9c6.jpeg)
