### ISSUE TITLE
Did you find someone to take over dpaste.org

### ISSUE THREAD

**Issue by diek** [DarrenOfficial/dpaste#161]
## Description
Did you find someone to take over dpaste.org
## Reason for task
You posted you were looking for a replacement. Did you find someone?

**Comment by DarrenOfficial** [comment]
yes, I took over dpaste.org. previously it was owned and maintained by @bartTC 
https://forum.darrennathanael.com/d/3-the-future-of-dpasteorg

**Comment by diek** [comment]
Thank you Darren, dpaste is my recommend pastebin, and I ask all of our Django FB group members to use it.
