### ISSUE TITLE
Auto format code

### ISSUE THREAD

**Issue by technomancy** [DarrenOfficial/dpaste#175]
## Description

There have been a lot of new languages and features added to Pygments; is there any chance we could see dpaste pull in a version that takes advantage of those? I want to recommend dpaste to people who write Fennel code, but the version of pygments currently in use on dpaste.org appears to be too old.

Thanks!

**Comment by DarrenOfficial** [comment]
Hey, I've updated https://dpaste.org pygments version to 2.11.

**Comment by technomancy** [comment]
Thanks!

It looks like the list of languages on dpaste does not cover all the languages supported by pygments. I guess maybe that is intentional since it's a very long list, but is there a way to get it to apply highlighting from a pygments-supported language that's not in the list? Or does the list just need to be regenerated?

**Comment by DarrenOfficial** [comment]
> It looks like the list of languages on dpaste does not cover all the languages supported by pygments. 

It's a really long list. I only added a few languages that I think is the most commonly used.
>  is there a way to get it to apply highlighting from a pygments-supported language that's not in the list?

There's probably a way to do it, I'll check it later if it's possible or not.

**Comment by technomancy** [comment]
Did you find a way to let the language be set to a pygments-supported option?

The pastebin ix.io lets you do this by appending the name of the language to the URL, like http://ix.io/abc/fennel and I wonder if something similar could work here.

**Comment by DarrenOfficial** [comment]
> Did you find a way to let the language be set to a pygments-supported option?

Yes. I've started working on it, the url would look something like this dpaste.org/foobar.py, dpaste.org/foobar.js

**Comment by technomancy** [comment]
To clarify, does this mean that there are no plans for dpaste to support languages that aren't in the dropdown?

**Comment by DarrenOfficial** [comment]
Not in the near future.

**Comment by technomancy** [comment]
OK, good to know; will look for another paste site then. good luck.
