### ISSUE TITLE
Js issue

### ISSUE THREAD

**Issue by JotaroKujo0525** [DarrenOfficial/dpaste#196]
Hello! I am kinda testing things on your website lately and I noticed that if I block javascript on your site, 2 icons will appear on `Paste snippets`. Also on mac, The js detection is kinda bugged and doesn't work properly

**Comment by DarrenOfficial** [comment]
it has something to do with https://github.com/DarrenOfficial/dpaste/blob/master/client/js/dpaste.js#L6-L7
I'll need to find a better way to detect if a user is using mac or windows
