### ISSUE TITLE
Dpaste is not compatible with pygments >= 2.12.0

### ISSUE THREAD

**Issue by by-cx** [DarrenOfficial/dpaste#208]
## Description

Dpaste is affected by this bug:

https://github.com/pygments/pygments/issues/2119

It crashes when something else than plain text is stored.

## Steps to reproduce

1. Install dpaste
2. Go to its URL
3. Select any language and hit Paste Snippet

## Expected result

The snippet is saved.

## Actual result

![Snímek obrazovky z 2022-06-02 00-06-20](https://user-images.githubusercontent.com/428000/171509933-116ea4d2-105e-4d75-b731-0d2fad1c8fd7.png)

**Comment by DarrenOfficial** [comment]
Hello, thanks for the info. I didn't notice this.

I will temporarily downgrade pygments until I found a solution to fix this issue.

**Comment by by-cx** [comment]
No problem, I noticed it during installation yesterday. Thanks for the fix.

**Comment by koobs** [comment]
I'd like to revive dpaste in the FreeBSD ports/package tree, which was removed due to pygments issue. Adding my +1 to this request to resolve with latest stable pygments. If you need any assistance/support, let us know. <3

**Comment by DarrenOfficial** [comment]
It is alive 😄

**Comment by koobs** [comment]
HOOOOOOOOOOOOOOORRRRRRRRRRRRRRRRRRRAAAAAAAAAAAAAAAAAAAAY THANK YOU @DarrenOfficial <3

**Comment by koobs** [comment]
@DarrenOfficial seeing lots of the following running tests. Let me know if you need help isolating. One tests traceback follows:


```
  File "/usr/ports/www/py-django-dpaste/work-py312/dpaste-16f229c/dpaste/highlight.py", line 153, in highlight
    return highlight(code_string, self.lexer, self.formatter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pygments/__init__.py", line 82, in highlight
    return format(lex(code, lexer), formatter, outfile)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pygments/__init__.py", line 64, in format
    formatter.format(tokens, realoutfile)
  File "/usr/local/lib/python3.12/site-packages/pygments/formatter.py", line 124, in format
    return self.format_unencoded(tokensource, outfile)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pygments/formatters/html.py", line 987, in format_unencoded
    source = self.wrap(source)
             ^^^^^^^^^^^^^^^^^
TypeError: NakedHtmlFormatter.wrap() missing 1 required positional argument: 'outfile'
```

Running Python 3.12 against Django 4.2 in case its relevant. ❤

**Comment by DarrenOfficial** [comment]
Found the issue, Pygments 2.19.1 requires explicit `outfile` param. PR soon

**Comment by DarrenOfficial** [comment]
Should be it

**Comment by koobs** [comment]
> Should be it

I may be missing something, but I've pulled master @ dc50fcdd4f and it's still showing 3 args for highlight() [1] from original code, and the commit is only showing a change in one hunk in highlight.py. The commit log message mentions many other changes and im assuming to other files too. git squash/merge/stage issue?

[1] https://github.com/DarrenOfficial/dpaste/blame/dc50fcdd4f6dde1fa3165aa5307e727a3fa6c70a/dpaste/highlight.py#L154
