### ISSUE TITLE
Saved snippet removable by anyone?

### ISSUE THREAD

**Issue by Cade66** [DarrenOfficial/dpaste#223]
Hi,

I've just published for the first time a snippet on https://paste.mozilla.org/
I closed the page, no cookies, no localStorage, opened the link and was surprised to notice I could delete the snippet.
This means anyone can delete a snippet without being the author?
Please explain this point which seems absurd.

Thanks.

**Comment by DarrenOfficial** [comment]
> This means anyone can delete a snippet without being the author?


That is correct; anyone, provided they know the direct URL of the snippets, can delete it.

See this commit for a reason why this is a feature https://github.com/DarrenOfficial/dpaste/commit/2b402680f8755f1c56253de62afac07194a97d8b

**Comment by Cade66** [comment]
OK, thanks for your quick reply.
I won't be using a pastebin which can be removed by anyone disagreeing, i.e., with my comment.
Say I'm on a forum, have a lengthy code, or comment, paste the snippet's url which then gets visited by either a mad mind or one that disagrees ... a click and off goes a snippet an author has maybe carefully crafted, published and that anyone can remove. Sorry to be straightforward but I've never encountered such an odd policy and have no intention of being submitted to it as well.
Good luck.
