### ISSUE TITLE
CORS problems make this unusable via javascript

### ISSUE THREAD

**Issue by beyarkay** [DarrenOfficial/dpaste#225]
## Description

Currently I can't fetch a paste that I POST to dpaste because the CORS header's aren't set to allow any origin. It would be amazing if I could POST a paste to dpaste, and then access that paste from a website I'm building.

## Acceptance Criteria

This would be fixed if I can go into my browser and execute:

```js
fetch('https://dpaste.org/KQn3b')
```

And not get an error message like:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://dpaste.org/KQn3b. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource. 
```

**Comment by DarrenOfficial** [comment]
Hello, I've added a CORS header set to allow any origin.

Please check if that resolved the issue for you.

**Comment by beyarkay** [comment]
Thanks so much!
