### ISSUE TITLE
Indentation messed up

### ISSUE THREAD

**Issue by vitobotta** [DarrenOfficial/dpaste#226]
## Description

Hi, I just built the Docker image from master and when I create a snippet in Ruby for example the indentation is gone, so I have to use the raw view which doesn't have any syntax highlighting. I found some previous issues about it and I was under the impression that it had been fixed but it doesn't seem to be the case for me.

## Environment

URL:

## Steps to reproduce

1. Create a snippet in Ruby, Python or other language
2.
3. ...

## Expected result

I would expect the code to look exactly as I pasted it into the editor, as far as indentation is concerned.

## Actual result

Indentation is messed up. See example here https://bin.botta.me/t1nd

Thanks

**Comment by DarrenOfficial** [comment]
![404](https://user-images.githubusercontent.com/55406094/215041946-f657a1d0-0bf3-4f40-b8a3-f9f8207694ae.png)

**Comment by vitobotta** [comment]
Oops, sorry - I forgot that about this issue and in the meantime I tried other alternatives because of the indentation issue. I very much prefer dpaste though, it's the better looking one :)

However I tried your instance now and indentation seems to work correctly, and the colors on the app are slightly different. Perhaps I was using the wrong Docker image? Which image should I be using with the latest updates?

**Comment by vitobotta** [comment]
This is the example with your instance https://dpaste.org/3hfoo

With mine all the leading whitespace was removed.

**Comment by vitobotta** [comment]
Hi @DarrenOfficial - I just built an image from master and it still looks different from your instance and the colors are different, see https://bin.botta.me/NqWK (I switched back to dpaste)

Are you using a branch other than master?

**Comment by DarrenOfficial** [comment]
> Are you using a branch other than master?

I am using the master branch + modifications to color & about. Other than that, the code is completely the same.

My Dockerfile
```dockerfile
FROM darrenofficial/dpaste:latest as prod

WORKDIR /app

# RUN pip install sentry-sdk
RUN ./manage.py migrate

COPY about.html dpaste/templates/dpaste/about.html
COPY local.py dpaste/settings/local.py
```

I see that you are using Cloudflare too. Check your settings to make sure it doesn't auto minimize the code, as that could be the reason that yours look different.

**Comment by vitobotta** [comment]
I have disabled minification in Cloudflare and it looks normal now, thanks! I should have thought about that. Closing :)
