### ISSUE TITLE
CloudFlare challenges from CLI (curl and such)

### ISSUE THREAD

**Issue by mathieu-aubin** [DarrenOfficial/dpaste#236]
## Description

Would love to have a way to whitelist my server's ip within cloudflare so i can share data between my mobile, home pc and linux server... right now, pasting from command line with curl, it seems i get sent to CF challenges and i cannot seem to be able to solve them from the command line... Maybe if i tunnel from home to server to CF...

**Comment by DarrenOfficial** [comment]
Hey, Cloudflare sometimes has false positive and there's not really much that I can do besides whitelisting the requesting IP. 

Do you have Dynamic IP or Static IP? 

If you have Dynamic send me your ISP /24 subnets, so I can whitelist it on CF, if you have a Static IP just send me that single IP, and I'll whitelist you.

Send the address(s) to noc@darrennathanael.com 👍🏼
