### ISSUE TITLE
Timed Out When Refreshing

### ISSUE THREAD

**Issue by some1ataplace** [DarrenOfficial/dpaste#248]
dpaste.org has timed out.
Reloading the page usually fixes it. Contact [Darren](mailto:me@darrennathanael.com) if this keep happening.
Bad gateway

The web server reported a bad gateway error.

    Ray ID: `<random ray id>`
    Your IP address: `<ip address>`
    Error reference number: 502
    Cloudflare Location: `<Location>`

Your access ID is `<random number>`

**Comment by DarrenOfficial** [comment]
This is now solved
