### ISSUE TITLE
Expire in 1 day instead of 24 hours

### ISSUE THREAD

**Issue by tansy** [DarrenOfficial/dpaste#251]
## Description

In combobox coding expiration time everything is in 1 units but a day is in hours, 24 hours. It's confusing, therefore I propose to use 'expire in 1 day' .

## Acceptance Criteria

I propose to use 'expire in 1 day' instead of 'expire in 24 hours'. Everyone know what a day is.

**Comment by DarrenOfficial** [comment]
Updated the prod config 🙂

![image](https://github.com/DarrenOfficial/dpaste/assets/55406094/9440c2dc-6ed3-4279-959f-7071d0a496ef)


The config file can be found here, although I'm not quite sure who set the text to 24 hours. 🤷🏼 
> https://github.com/DarrenOfficial/dpaste/blob/master/dpaste/settings/local.py.example

**Comment by tansy** [comment]
Looks good.
