### ISSUE TITLE
API response when size limit is reached 

### ISSUE THREAD

**Issue by ShalokShalom** [DarrenOfficial/dpaste#255]
The API gives currently this error, when the size limit is reached: 

```
<!doctype html>
<html lang="en">
<head>
<title>Bad Request (400)</title>
</head>
<body>
<h1>Bad Request (400)</h1><p></p>
</body>
</html>
```

I suggest a precise error message like the one in the web UI.

**Comment by DarrenOfficial** [comment]
This error is not thrown out by dpaste itself, rather OpenResty; I'll re-configure it with (#256) so it shows the real error message

**Comment by DarrenOfficial** [comment]
API should return a precise error message now.
