### ISSUE TITLE
Output aligns to the left with plain text

### ISSUE THREAD

**Issue by ShalokShalom** [DarrenOfficial/dpaste#256]
Do you know, why this aligns on the left now?

https://dpaste.org/JP32d

It happens only with plain text and it seems to not respect indendation:

https://dpaste.org/5oSPm

**Comment by DarrenOfficial** [comment]
I see the problem and I can replicate it

**Comment by DarrenOfficial** [comment]
Pushing to prod once it finished building. Sorry for the two-month delay 😞
