### ISSUE TITLE
Syntax support for fish and Julia

### ISSUE THREAD

**Issue by ShalokShalom** [DarrenOfficial/dpaste#257]
Hi there 👍🏻 

You use Pygments for syntax highlighting, yes?

I use Fish and Julia, who are both supported by it. 
Do you limit the choice of languages for dpaste, or is there work to do?

**Comment by DarrenOfficial** [comment]
> You use Pygments for syntax highlighting, yes?

Yes, 

>  Do you limit the choice of languages for dpaste, or is there work to do?

Yup, the list is shorten; I'll add Fish & Julia to the main local.py soon so you can use it :-)

**Comment by ShalokShalom** [comment]
Thanks a lot 👍🏼
