### ISSUE TITLE
dpaste.org has timed out

### ISSUE THREAD

**Issue by some1ataplace** [DarrenOfficial/dpaste#258]
Reloading the page usually fixes it. Contact [Darren](mailto:me@darrennathanael.com) if this keep happening.
Connection timed out

The initial connection between Cloudflare's network and the origin web server timed out. As a result, the web page can not be displayed.

**Comment by DarrenOfficial** [comment]
Please email directly in case of future [issues regarding availability](https://status.dpaste.org/), thanks

-darren
