### ISSUE TITLE
Captcha Missing

### ISSUE THREAD

**Issue by some1ataplace** [DarrenOfficial/dpaste#261]
Pastes are unable to be submitted. The captcha checkbox is missing.

dpaste.org is verifying your request.
Solve the challenge below to be redirected to the requested content. [Status Page](https://status.darrennathanael.com/)
::CAPTCHA_BOX::****

**Comment by DarrenOfficial** [comment]
Hello, is this still happening?

Pastes are working fine from a residential ASN; Cloudflare might think something sus is going on, or they franned something again with the captcha.

I tried forcing captcha on my ASN and the box is appearing normally; please let me know your Access ID & Time so I can narrow it down.
![image](https://github.com/user-attachments/assets/2a46b3dd-72e5-43dd-af92-8614cc1d7f55)

& What request method are you using? Browser; if so which Firefox, Chrome, Brave ect ect?

**Comment by some1ataplace** [comment]
It works fine with very low amount of text content in the submitted pastes. However, when I input a large amount of text in the editor and submit, it fails to show a captcha. 

Happens on both Chrome and Firefox. 

8eb786ff5815597a

**Comment by DarrenOfficial** [comment]
Ah I see the issue, it should've lead you to the block page; but I guess that's Cloudflare for ya.

You're triggering `Cloudflare Specials` ruleset; which applies to Enterprise customer I suppose; I'll try to disable this & let you know once it's off

![image](https://github.com/user-attachments/assets/dae7cb15-7c70-4b70-91a0-00de11e660ee)

**Comment by DarrenOfficial** [comment]
Found the ruleset, disabled it. Please check & see if it is still happening; let me know your Access ID if it still does.

**Comment by some1ataplace** [comment]
Still happens.

8eb7a0e27fc20790

**Comment by DarrenOfficial** [comment]
Ugh, missed a button press. Turns out it's a three-step process, Manage Ruleset > Save RuleSet > Deploy To Cloudflare Global WAF...

It' should be disabled now.

**Comment by some1ataplace** [comment]
Thank you, that worked.

**Comment by some1ataplace** [comment]
@DarrenOfficial I am running into this problem again. 

90ed32be0d8bc5b1

**Comment by Farewe1ll** [comment]
I'm pity to find that this problem is happening again, on 27th, Mar. 2025 with my access id 926ced5aabd0858e.
I'm finding your pastebin website quite easy and plain to use, and I hope I'll get better experience after this little problem.
...And many thks for your website!

<img width="739" alt="Image" src="https://github.com/user-attachments/assets/39ab198a-3f87-4e8a-a118-7c44ba99410b" />

**Comment by DarrenOfficial** [comment]
I'll take Cloudflare Ruleset offline for the main website until I figure out what's triggering these issues. Please check again

**Comment by Farewe1ll** [comment]
***@***.***

**Comment by Farewe1ll** [comment]
> I'll take Cloudflare Ruleset offline for the main website until I figure out what's triggering these issues. Please check again

Thanks a lot. Your pastebin is really awsome and recently I'm finding it an indispensable pastebin. And the situation above haven't appeared since then. I'm quite appreciated!
